#!/usr/bin/env python3
"""Freeze the registered MCP tool surface to tests/golden/tool_surface.json.

This is the count-anchor for the auto-discovery registration refactor
(the independent witness that catches a whole-service symmetric miss,
where the per-service ``_expected_tools.py`` declarations AND the
discovered/registered set both happen to drop the same folder).

Run it like uv.lock: regenerated by an explicit human command, then
PR-reviewed as a diff. NEVER auto-regenerated by the test suite — the
golden test ASSERTS against it; if a tool is added/removed/renamed,
the diff to this file is the reviewed proof of the surface change.

    python scripts/freeze_tool_surface.py        # rewrite the golden
    python scripts/freeze_tool_surface.py --check # exit 1 if stale (CI use)

CRITICAL — MUST be run as a FILE (``python scripts/freeze_tool_surface.py``),
NEVER as ``python -c "..."``. Under an editable / ``src``-layout install,
``python -c`` cannot resolve the ``google_docs_mcp.services`` subpackage
namespace (``pkgutil`` finds nothing, ``import
google_docs_mcp.services.X`` raises ModuleNotFoundError) — a Python
packaging artifact of editable + src-layout + ``-c``, entirely upstream
of (and unrelated to) the tool-registration mechanism. File execution
(which is how prod's console-script entry, CI, and this script all run)
resolves the subpackage correctly and registers the full surface. See
the auto-discovery refactor PR + ADR for the full investigation.
"""
from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

# tests/golden/tool_surface.json — repo-root-relative.
_GOLDEN_PATH = (
    Path(__file__).resolve().parent.parent
    / "tests"
    / "golden"
    / "tool_surface.json"
)


def current_tool_surface() -> list[str]:
    """Return the sorted list of every registered tool name.

    Imports ``google_docs_mcp.server`` (which runs auto-discovery as a
    module-load side effect post-refactor; pre-refactor it ran the
    explicit bottom-of-file side-effect imports). Either way, by the
    time this returns, the full surface is registered on the live
    ``mcp`` instance.
    """
    from google_docs_mcp.server import mcp

    tools = asyncio.run(mcp.list_tools())
    return sorted(t.name for t in tools)


def _write_golden(names: list[str]) -> None:
    _GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    # Trailing newline + 2-space indent so the file diffs cleanly and
    # matches the project's JSON-artifact convention.
    _GOLDEN_PATH.write_text(json.dumps(names, indent=2) + "\n", encoding="utf-8")


def _read_golden() -> list[str]:
    return json.loads(_GOLDEN_PATH.read_text(encoding="utf-8"))


def main(argv: list[str]) -> int:
    check_only = "--check" in argv
    current = current_tool_surface()

    if check_only:
        if not _GOLDEN_PATH.exists():
            print(
                f"golden surface file missing: {_GOLDEN_PATH}\n"
                f"run `python scripts/freeze_tool_surface.py` to create it.",
                file=sys.stderr,
            )
            return 1
        frozen = _read_golden()
        if frozen == current:
            print(f"tool surface up to date ({len(current)} tools)")
            return 0
        added = sorted(set(current) - set(frozen))
        removed = sorted(set(frozen) - set(current))
        print(
            "tool surface DRIFT vs golden:\n"
            f"  added (registered, not in golden):   {added}\n"
            f"  removed (in golden, not registered): {removed}\n"
            f"  golden={len(frozen)} registered={len(current)}\n"
            f"If intentional, run `python scripts/freeze_tool_surface.py` "
            f"and commit the diff.",
            file=sys.stderr,
        )
        return 1

    _write_golden(current)
    print(f"wrote {_GOLDEN_PATH} ({len(current)} tools)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
